name: Continuous integration checks

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CONFIG_PATH: ${{ github.workspace }}/scripts/config.json
    steps:
      - uses: actions/checkout@v3

      - name: Install anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}

      - name: Install dependencies & setup
        run: |
          yarn -v
          yarn
          yarn setup

      

          - name: Check formatting
          run: yarn check:prettier

      - name: Build all packages
        run: |
          yarn build

     - name: Build all packages
        run: |
          yarn build
