name: Docker Build push

on: 
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


env:
  GIT_REF: ${{ github.head_ref || github.ref_name }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_URL }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and push
        run: ./.github/scripts/build_and_push.sh
        env:
          DOCKER_IMAGE_NAME: "registry.digitalocean.com/karpatkey/defi-kit"
          DOCKERFILE: "./Dockerfile"
